export const TRAER_TODAS='traer_tareas'
export const CARGANDO='tareas_cargando'
export const ERROR='tareas_error'
export const CAMBIO_USUARIO_ID='cambiar_usuario_id'
export const CAMBIO_TITULO='cambiar_usuario_titulo'
export const GUARDAR='guardar_tareas'
export const CHECKED='cambiar_check'
export const LIMPIAR='limpiar_campos'